### ISSUE TITLE
Recursive relations/references in schema's cause `Maximum call stack exceeded` error

### ISSUE THREAD

**Issue by ThaDaVos** [seriousme/fastify-openapi-glue#397]
Our OpenAPI definition contain indirect recursive references  as we've got relations going back and forth between models (on which the schema's are based) - this in turn causes fastify to crash with `Maximum call stack exceeded` error, also can be seen here:
https://github.com/fastify/help/issues/659

Maybe a quick way to solve it would be the option to disable the schema generation?

**Comment by seriousme** [comment]
Hi,

thanks for asking.

Disabling schema extraction would basically void the purpose of the plugin ;-)

The only this plugin does is extract the relevant parts from the OAS schema and pass them to fastify. If Fastify has a regression as hinted on by Matteo then I'd wait for them to fix that first. Unfortunately the OP did not follow up with a runnable example.

If you can provide a minimal runnable example using fastify openapi glue then I'm happy to check it out.

Kind regards,
Hans

**Comment by seriousme** [comment]
Btw: if you are looking for a quick patch then you should be able to provide a custom [validator compiler](https://www.fastify.io/docs/latest/Reference/Server/#validatorcompiler) and [serialization compiler](https://www.fastify.io/docs/latest/Reference/Server/#serializercompiler) that takes the schema and returns a function that always returns true ;-)

**Comment by ThaDaVos** [comment]
I'll try to create a minimal runnable example which contains the problem later today (hopefully) - I saw the other issue is closed already

**Comment by seriousme** [comment]
Hi,

I created a minimal example:

```json
{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "http://localhost/v2"
    }
  ],
  "info": {
    "title": "Recursive Test specification",
    "description": "testing the fastify openapi glue using recursive schema",
    "version": "0.1.0"
  },
  "paths": {
    "/recursive": {
      "post": {
        "operationId": "postRecursive",
        "summary": "Test recursive parameters",
        "responses": {
          "200": {
            "description": "ok"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/bodyObject"
              }
            }
          },
          "required": true
        }
      }
    }
  },

  "components": {
    "schemas": {
      "bodyObject": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "str1": {
            "type": "string"
          },
          "obj1": {
            "$ref": "#/components/schemas/bodyObject"
          }
        },
        "required": [
          "str1"
        ]
      }
    }
  }
}
```

And its a bug in the plugin that causes your trouble :-(

What happens is that the parser resolves the "$ref" so the rest of the plugin is not bothered by refs. Unfortunately this goes belly up on recursive references as AJV cannot detect the recursion anymore :-(

The solution is to have the parser not resolve the refs but to add them to the schema.
As soon as I have a bit more time I plan on tackling this.Probably over the weekend.

Sorry for the inconvenience.

Kind regards,
Hans

**Comment by ThaDaVos** [comment]
Thanks for finding it yourself @seriousme - I thought about looking into it this weekend because yesterday I didn't have the time as I was first working on an issue in another package I am using 😂

**Comment by seriousme** [comment]
OK, I think I got a working solution in https://github.com/seriousme/fastify-openapi-glue/tree/test-recursive.
Would you mind giving it a spin to see if it resolves your issue ?

Kind regards,
Hans

**Comment by ThaDaVos** [comment]
Quick question - how can I test that version? Is it on NPM or do I have to build it myself?

**Comment by ThaDaVos** [comment]
Apperently this is what I needed:
`npm install  https://github.com/seriousme/fastify-openapi-glue.git#test-recursive`

**Comment by ThaDaVos** [comment]
I am not getting `Maximum call stack exceeded` errors at the moment but it fails resolving the schema:
`Failed building the serialization schema for GET due to error Cannot find reference` - I'll check into this to be sure that it's not an error with my spec

**Comment by ThaDaVos** [comment]
Okay, I dug into it - but I think recursive loops are not handled correctly now, seems they go missing - at least for me - as I get an error that a reference is missing but when I follow the path down - it ends at a `$ref` which is probably not resolved or removed now

**Comment by ThaDaVos** [comment]
I've fixed it on my side by dereferencing the whole OpenAPI schema before passing it into the plugin - using a simple trick with JSON.stringify and the `replacer` option

**Comment by seriousme** [comment]
> I've fixed it on my side by dereferencing the whole OpenAPI schema before passing it into the plugin - using a simple trick with JSON.stringify and the `replacer` option

That should not be required. Can you provide a use case so we can check what still needs to be fixed ?

The current testcase is:
https://github.com/seriousme/fastify-openapi-glue/blob/test-recursive/test/test-openapi-v3-recursive.json

Kind regards,
Hans

**Comment by ThaDaVos** [comment]
This is the OpenAPI docs I am talking about:
https://pastebin.com/agCuqYDN

The password is your username and it will be removed after being viewed (so it's best to copy it and store it locally)

**Comment by seriousme** [comment]
Hi,

thanks for the file, I created a local copy. It is rather large with many refs so I might need some time to figure it out ;-)

Kind regards,
Hans

**Comment by seriousme** [comment]
Small update:

I did some digging and the problem seems to be in refs with a number in it :-(

E.g. after the recursion removal algorithm runs the following response schema is generated for fastify:
(removed some details to protect the privacy of your schema ;-))
```json
{
   "response": {
          "200": {
            "type": "string"
          },
          "401": {
            "$ref": "#/200"
          },
          "403": {
            "$ref": "#/200"
          },
          "404": {
            "$ref": "#/200"
          },
          "$id": "http://example.com/fastifySchema"
        }
}
```

Then AJV complains that it cannot resolve `#/200`. From what I see is '#/200' a valid JSON pointer, but I need to dig a bit deeper.

Kind regards,
Hans

**Comment by seriousme** [comment]
Another small update:

The reason why `#/200` fails is that AJV only gets the schema for the specific response type, e.g. for a 401:
```json
{
  "$ref": "#/200"
 }
```

And then the `#/200` cannot be resolved. So the algorithm to unravel potential loops needs to be tweaked to produce the right results. This is why its good that you mentioned that it did not work correctly !

Thanks,
Hans

**Comment by ThaDaVos** [comment]
Maybe I should share my code which I use to prepare the schema, it uses a little logic to remove circular references which are back references in the same path (only up) - seems to work fine - currently going through my schema fixing a few wrong typings, "object" instead of "array"

If you want this revolver i used to remove the back references, please ask - as your current implementation seemed like it was nuking all circular references, even correct ones (i may be wrong)

**Comment by ThaDaVos** [comment]
I am using the following, to parse the downloaded `.json` from my schema and turn it into a valid `.ts` file which I include and use as schema - as you can see, it only removes circular dependecies if they are on the same path (as these are the issue givers most of the time) - I did this, as paths like x->y->x->y - are almost never needed in our system because you would be stupid to load Resource X with Relation Y with Relation X (as this X is the same as the first X 99,99% of the time):

```Typescript
import $RefParser from "@apidevtools/json-schema-ref-parser";

const dereferenced = await $RefParser.dereference(json);

function replacerWithPath(replacer) {
  let m = new Map();

  return function (field, value) {
    const path =
      m.get(this) + (Array.isArray(this) ? `[${field}]` : "." + field);
    if (value === Object(value)) m.set(value, path);
    return replacer.call(
      this,
      field,
      value,
      path.replace(/undefined\.\.?/, "")
    );
  };
}

function getCircularReplacer(
  seen = new WeakMap<object, string[]>(),
  pathPrefix = "",
  depth = 0
) {
  return replacerWithPath(function (
    key: string,
    value: Record<string, never> | string | number | null | undefined,
    path: string
  ) {
    if (
      typeof value === "object" &&
      value !== null &&
      !(value instanceof Boolean) &&
      !(value instanceof Date) &&
      !(value instanceof Number) &&
      !(value instanceof RegExp) &&
      !(value instanceof String)
    ) {
      if (key === "") {
        return value;
      }

      if (pathPrefix !== "") {
        path = `${pathPrefix}.${path}`;
      }

      if (seen.has(value)) {
        const seenAts = seen.get(value) ?? [];

        if (
          seenAts.some(
            (seenAt: string) => path !== seenAt && path.startsWith(seenAt)
          )
        ) {
          return undefined;
        }

        seenAts.push(path);
        seen.set(value, seenAts);

        return JSON.parse(
          JSON.stringify(value, getCircularReplacer(seen, path, depth + 1))
        );
      } else if (
        Object.prototype.hasOwnProperty.call(value, "type") &&
        Object.prototype.hasOwnProperty.call(value, "items") &&
        value.type === "array" &&
        seen.has(value.items)
      ) {
        const seenAts = seen.get(value.items) ?? [];

        if (
          seenAts.some(
            (seenAt: string) => path !== seenAt && path.startsWith(seenAt)
          )
        ) {
          return undefined;
        }

        seenAts.push(path);
        seen.set(value.items, seenAts);

        return JSON.parse(
          JSON.stringify(
            value.items,
            getCircularReplacer(seen, path, depth + 1)
          )
        );
      } else {
        seen.set(value, [path]);
      }
    }

    return value;
  });
}

const specification = JSON.stringify(
  dereferenced,
  getCircularReplacer(),
  2
)?.replace(/"([a-zA-z0-9_]+)":/gm, "$1:");

const specificationFile = `export const specification = ${specification};`;
```

**Comment by ThaDaVos** [comment]
I've change a few lines in the above code-snippet as I found an error in them

**Comment by seriousme** [comment]
Thx, the deref function seems to work. 
E.g. when I submit the schema for the first '200' response to AJV it works ok.
However submitting the same result as part of a fastify route it complains that the $ref path does not exist.

I just need some time to do a bit more testing to iron out the last wrinkle ;-)

Kind regards,
Hans

**Comment by ThaDaVos** [comment]
@seriousme - found something else also - maybe you should filter out `example` from the schema too?
`Failed building the validation schema for {METHOD}: {PATH}, due to error strict mode: unknown keyword: "example"`

**Comment by seriousme** [comment]
This  error is fairly easy to fix by applying:


```javascript
const noStrict = {
  ajv: {
    customOptions: {
      strict: false,
    },
  },
};
const fastify = Fastify(noStrict);
```

But its a good suggestion indeed to have the plugin remove the examples so people don't have to add AJV flags.

Kind regards,
Hans

**Comment by seriousme** [comment]
I checked the OAS 3.1 spec and it seems to suggest that `example` is only allowed outside the schema

For parameters: https://spec.openapis.org/oas/v3.1.0#fixed-fields-9 
Responses fall under the header object which is a variant of the parameter object.

For components: https://spec.openapis.org/oas/v3.1.0#fixed-fields-5

`examples` however (mind the `s`) are allowed within JSON schema: 

> New in draft 6 The examples keyword is a place to provide an array of examples that validate against the schema. This isn’t used for validation, but may help with explaining the effect and purpose of the schema to a reader. Each entry should validate against the schema in which it resides, but that isn’t strictly required. 

https://json-schema.org/understanding-json-schema/reference/generic.html

That would imply that AJV is correct in rejecting the `example` attribute in a schema.

What do you think ?

Kind regards,
Hans

**Comment by ThaDaVos** [comment]
That was one thing I couldn't get clear from the docs, i changed my code to use examples instead of example everywhere now - strange thing, swagger ui didn't mind

**Comment by seriousme** [comment]
Swagger UI seems to be rather liberal in what it accepts ;-)

I just pushed some updates to the test-recursive branch. Most notably I added a recursive response object to https://github.com/seriousme/fastify-openapi-glue/blob/test-recursive/test/test-openapi-v3-recursive.json
That test works fine.

Could you give it a try with your (updated) spec and if it fails come up with a small (ie. way smaller than 11K lines ;-)) example of what fails ?

Kind regards,
Hans

**Comment by ThaDaVos** [comment]
One thing I notice is that your recursion differs from mine - yours is `a -> a` while mine is `a -> b -> a` - hopefully this doesn't make a huge difference, but it is one

I'll try your above one without dereferencing the schema myself and let you know

**Comment by ThaDaVos** [comment]
Sadly it doesn't seem to work - I am still getting `not found` errors - maybe the best solution would be to fully dereference the schema based on my circular reference code above - so no references are used inside the schema? Or find a better way to fix these references?

I'll give you a new version of my full schema (in json format and not dereferenced) so you can see for your self what it fails on (I am having difficulties creating a smaller snippet which also fails as I don't really have to time yet to fully dive into it)

Same conditions as the first pastbin - password is your username and it's burned after read:
https://pastebin.com/qu5CUryE

**Comment by seriousme** [comment]
I have released the current code as version 4.0.1 as I can't find the issue with your specification.

I have added more complex relations to the test scenario and that still works, see:
https://github.com/seriousme/fastify-openapi-glue/blob/ac4fe6b9add116a6290d59564482b8ae0189249c/test/test-openapi-v3-recursive.json

Should you find the cause of the issue with your specification then I am more than happy to add another fix.
For now it just takes me too much time to figure it out with only the 11K spec.

Kind regards,
Hans
